<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements of hook_element_info_alter().
 */
function zm_ckeditor_element_info_alter(&$type) {
  // Change text format processing on elements to our version.
  if (isset($type['text_format'])) {
    $type['text_format']['#process'][] = 'zm_ckeditor_filter_process_format';
  }
}
/**
 * Callback for processing the text_format element
 */
function zm_ckeditor_filter_process_format($element) {
  // Do not auto submit the form due to changes of the filter
  $element['format']['format']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  // Do not show the guidelines and help text for text formatters
  // Also format this all a bit different so that it looks right
  $element['format']['#weight'] = 1;
  $element['format']['#prefix'] = '<div class="format-toggle clearfix">';
  $element['format']['#suffix'] = '</div><div class="clearfix"></div>';
  unset($element['format']['#type']);
  $element['format']['format']['#title'] = 'Editor: ';
  $element['format']['help']['#access'] = FALSE;
  $element['format']['guidelines']['#access'] = FALSE;

  return $element;
}
